app:
  replicas: 6
  env: dev
  container:
    image: deekshithsn/ui

  computerc:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi

hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 4
  cpuuti: 50


config:
  name: config.yaml
  data:
    timeout: 2s
    logfile: /app/var/log.txt
    database:
      ip: 10.20.30.40
      name: ui-prod 